# Generated by Django 3.1.7 on 2021-05-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
