# Generated by Django 3.1.7 on 2021-05-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210519_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='id_boost',
            field=models.IntegerField(default=0),
        ),
    ]
