# Generated by Django 3.1.7 on 2021-05-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_boost_id_boost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boost',
            name='id_boost',
        ),
        migrations.AlterField(
            model_name='boost',
            name='mainCycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='user_profile.maincycle'),
        ),
    ]
