# Generated by Django 3.1.7 on 2021-05-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20210522_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='id_boost',
            field=models.IntegerField(default=0),
        ),
    ]
