# Generated by Django 3.1.7 on 2021-05-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_boost_id_boost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boost',
            name='id_boost',
        ),
        migrations.AddField(
            model_name='boost',
            name='level_boost',
            field=models.IntegerField(default=0),
        ),
    ]
